name: Update Token

on:
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - name: Update Token
        env:
          ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
        run: |
          for i in {1..3}; do
            response=$(curl -s -X GET \
              -H "X-API-Key: $ADMIN_API_KEY" \
              https://api.qubic.site/api/update-token)
            
            if echo "$response" | grep -q '"success":true'; then
              echo "Token update successful"
              exit 0
            fi
            
            echo "Attempt $i failed, waiting before retry..."
            sleep 10
          done
          
          echo "All attempts failed"
          exit 1
